### PR TITLE
udevdir fix

### PR DESCRIPTION
**Pull request by paul-jewell**
Added location definition for udevdir in package/Linux.mk

### CODE REVIEW

**Comment by parched** [comment]
This is not needed unless an option to install the udev rules is added.

**Comment by paul-jewell** [comment]
I added the directory so the mkdir doesn't fail. Do you think it would be better to make the mkdir command condition on udevdir being defined?

**Comment by parched** [comment]
I mean there is no point installing the udev dir if we don't install rules to it. So what you had before just deleting the line was better

**Comment by paul-jewell** [comment]
I have closed this, and issues a new pull request (#25) with the udevdir line deleted.

**Pull request closed without merging**
