### PR TITLE
Remove op from gcs dir structure

### PR DESCRIPTION
**Pull request by parched**
Moved the openpilotgcs tree to gcs

### CODE REVIEW

**Comment by parched** [comment]
We should merge this sooner rather than later if it is going in because any time someone adds a gcs file there will be a conflict

**Comment by parched** [comment]
This will conflict with other PRs I think. But review anyway and when we are happy I will fix it up, then merge straight away so it doesn't conflict again

**Comment by filnet** [comment]
looks good. not tested.

**Comment by parched** [comment]
Merged

**Pull request closed without merging**
