### PR TITLE
skarlsso/LP-26_update_welcome_page_plugin

### PR DESCRIPTION
**Pull request by skarlsso**
Show LibrePilot information on the welcome page.

* Populate the "Project Activity" section with commits in 'next'
* Populate the "Project News" section with News items from the forum

### CODE REVIEW

**Comment by skarlsso** [comment]
screen shot 2015-07-16 at 22 52 04

**Comment by filnet** [comment]
There's a "OpenPilot Websites" in the screenshot above.

**Comment by parched** [comment]
I haven't tested, but looks good to me.

**Comment by AlessioMorale** [comment]
I've made a followup Issue https://github.com/librepilot/LibrePilot/issues/43

**Comment by skarlsso** [comment]
I'll change the "OpenPilot Websites" into "LibrePilot Websites". Thanks @filnet!

**Comment by parched** [comment]
I think just Websites might be better but up to you

**Comment by AlessioMorale** [comment]
websites seems fine.
alternatively  that line may be removed altogeter

**Comment by skarlsso** [comment]
screen shot 2015-07-19 at 13 35 27

**Comment by skarlsso** [comment]
screen shot 2015-07-19 at 13 53 54

**Pull request merged**
